export const GET_DATA = 'GET_DATA';
export const GET_DATA_ATTEMPT = 'GET_DATA_ATTEMPT';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';
export const ON_EMAIL_CHANGE = 'ON_EMAIL_CHANGE';
export const ON_PASSWORD_CHANGE = 'ON_PASSWORD_CHANGE';
export const SUBMIT_DATA = 'SUBMIT_DATA';
export const SUBMIT_DATA_ATTEMPT = 'SUBMIT_DATA_ATTEMPT';
export const SUBMIT_DATA_SUCCESS = 'SUBMIT_DATA_SUCCESS';
export const SUBMIT_DATA_FAIL = 'SUBMIT_DATA_FAIL';

